### ISSUE TITLE
Half-red Dragon Veteran

### ISSUE THREAD

**Issue by sparky1088** [RiasKlein/MonsterLookup#40]
Parry (as well as the CR I believe) need to be fixed.
This is from the MM errata http://media.wizards.com/2015/downloads/dnd/MM_Errata.pdf
I am not sure how up to date the rest of the monsters are and if needed I can fork this and send my file for this particular one as i just cloned it for a simple html server I run with the stats on it (had it a while and only noticed because I had questions about making other half dragon races)

**Comment by RiasKlein** [comment]
Hi sparky1088,

It seems that I do have quite a few outdated things that require fixing. I hope to get fixes out in a future update.

Thanks for bringing this to my attention!

**Comment by RiasKlein** [comment]
Changes have been made according to the Monster Manual Errata. 

Enjoy ^.^
